/**
 * Admin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LanguageWriterModelContract { 
    name?: string | null;
    code?: string | null;
    _native?: string | null;
    rtl?: boolean | null;
    isDefault?: boolean | null;
    isEnabled?: boolean | null;
}

