/**
 * Identities.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppWriterModelContract { 
    name?: string | null;
    description?: string | null;
    code?: string | null;
    applicationType?: string | null;
    clientId?: string | null;
    clientSecret?: string | null;
    consentType?: string | null;
    displayName?: string | null;
    clientType?: string | null;
    permissions?: Array<string> | null;
    postLogoutRedirectUris?: Array<string> | null;
    redirectUris?: Array<string> | null;
    requirements?: Array<string> | null;
}

