/**
 * Identities.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChallengeDefinitionReduceModelContract } from './challengeDefinitionReduceModelContract';
import { ChallengeState } from './challengeState';


export interface ChallengeReaderModelContract { 
    id?: string | null;
    startDateTime?: string | null;
    endDateTime?: string | null;
    state?: ChallengeState;
    createdBy?: string | null;
    created?: string | null;
    lastModifiedBy?: string | null;
    lastModified?: string | null;
    organizationId?: string | null;
    visibility?: string | null;
    challengeDefinition?: ChallengeDefinitionReduceModelContract;
    user?: any | null;
    selectedProgrammingLanguage?: any | null;
}
export namespace ChallengeReaderModelContract {
}


