/**
 * Identities.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChallengeDefinitionState } from './challengeDefinitionState';


export interface ChallengeDefinitionReduceModelContract { 
    id?: string | null;
    title?: string | null;
    resume?: string | null;
    state?: ChallengeDefinitionState;
    description?: string | null;
    instruction?: string | null;
    score?: number | null;
    timeLimit?: number | null;
    withLimit?: boolean | null;
}
export namespace ChallengeDefinitionReduceModelContract {
}


