/**
 * Identities.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChallengeState } from './challengeState';


export interface ChallengeWriterModelContract { 
    startDateTime?: string | null;
    endDateTime?: string | null;
    state?: ChallengeState;
    challengeDefinitionId: string;
    userId: string;
    selectedProgrammingLanguageId: string;
    sourceCode: string;
}
export namespace ChallengeWriterModelContract {
}


