/**
 * Identities.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OrganizationEvent = 0 | 1;

export const OrganizationEvent = {
    NUMBER_0: 0 as OrganizationEvent,
    NUMBER_1: 1 as OrganizationEvent
};

