/**
 * Identities.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Email } from './email';
import { PhoneNumber } from './phoneNumber';


export interface PersonWriterModelContract { 
    firstName?: string | null;
    lastName?: string | null;
    dateOfBirth?: string | null;
    emails?: Array<Email> | null;
    phoneNumbers?: Array<PhoneNumber> | null;
    ownerId?: string | null;
}

