/**
 * Identities.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizItemOptionReduceModelContract } from './quizItemOptionReduceModelContract';
import { QuestionReduceModelContract } from './questionReduceModelContract';
import { QuizReduceModelContract } from './quizReduceModelContract';


export interface QuizItemReaderModelContract { 
    id?: string | null;
    answer?: string | null;
    submit?: boolean | null;
    correct?: boolean | null;
    score?: number | null;
    createdBy?: string | null;
    created?: string | null;
    lastModifiedBy?: string | null;
    lastModified?: string | null;
    quiz?: QuizReduceModelContract;
    question?: QuestionReduceModelContract;
    quizItemOptions?: Array<QuizItemOptionReduceModelContract> | null;
}

