/**
 * Identities.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizReduceModelContract } from './quizReduceModelContract';
import { RepositoryReduceModelContract } from './repositoryReduceModelContract';
import { ChallengeReduceModelContract } from './challengeReduceModelContract';


export interface SessionReaderModelContract { 
    id?: string | null;
    createdBy?: string | null;
    created?: string | null;
    lastModifiedBy?: string | null;
    lastModified?: string | null;
    organizationId?: string | null;
    visibility?: string | null;
    quizzes?: Array<QuizReduceModelContract> | null;
    challenges?: Array<ChallengeReduceModelContract> | null;
    repositories?: Array<RepositoryReduceModelContract> | null;
    user?: any | null;
}

