/**
 * Kodin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { KodinApiConfiguration }                                     from '../kodin.api.configuration';



export interface DeleteEndPointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: KodinApiConfiguration;

    /**
     *
     *
     * @param id
     */
    challengeDefinitionsIdDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     *
     *
     * @param id
     */
    challengesIdDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     *
     *
     * @param id
     */
    questionsIdDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     *
     *
     * @param id
     */
    quizDefinitionsIdDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     *
     *
     * @param id
     */
    quizzesIdDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     *
     *
     * @param id
     * @param quizId
     */
    quizzesQuizIdQuizItemsIdDelete(id: string, quizId: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     *
     *
     * @param id
     */
    repositoriesIdDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     *
     *
     * @param id
     */
    reviewsIdDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     *
     *
     * @param id
     */
    sessionsIdDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

}
