/**
 * Kodin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChallengeDefinitionReaderModelContract } from '../model/models';
import { ChallengeReaderModelContract } from '../model/models';
import { QuestionReaderModelContract } from '../model/models';
import { QuizDefinitionReaderModelContract } from '../model/models';
import { QuizItemReaderModelContract } from '../model/models';
import { QuizReaderModelContract } from '../model/models';
import { RepositoryReaderModelContract } from '../model/models';
import { ReviewReaderModelContract } from '../model/models';
import { SessionReaderModelContract } from '../model/models';


import { KodinApiConfiguration }                                     from '../kodin.api.configuration';



export interface GetByIdEndPointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: KodinApiConfiguration;

    /**
     *
     *
     * @param id
     */
    challengeDefinitionsIdGet(id: string, extraHttpRequestParams?: any): Observable<ChallengeDefinitionReaderModelContract>;

    /**
     *
     *
     * @param id
     */
    challengesIdGet(id: string, extraHttpRequestParams?: any): Observable<ChallengeReaderModelContract>;

    /**
     *
     *
     * @param id
     */
    questionsIdGet(id: string, extraHttpRequestParams?: any): Observable<QuestionReaderModelContract>;

    /**
     *
     *
     * @param id
     */
    quizDefinitionsIdGet(id: string, extraHttpRequestParams?: any): Observable<QuizDefinitionReaderModelContract>;

    /**
     *
     *
     * @param id
     */
    quizzesIdGet(id: string, extraHttpRequestParams?: any): Observable<QuizReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param quizId
     */
    quizzesQuizIdQuizItemsIdGet(id: string, quizId: string, extraHttpRequestParams?: any): Observable<QuizItemReaderModelContract>;

    /**
     *
     *
     * @param id
     */
    repositoriesIdGet(id: string, extraHttpRequestParams?: any): Observable<RepositoryReaderModelContract>;

    /**
     *
     *
     * @param id
     */
    reviewsIdGet(id: string, extraHttpRequestParams?: any): Observable<ReviewReaderModelContract>;

    /**
     *
     *
     * @param id
     */
    sessionsIdGet(id: string, extraHttpRequestParams?: any): Observable<SessionReaderModelContract>;

}
