/**
 * Kodin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChallengeDefinitionReaderModelContract } from '../model/models';
import { ChallengeDefinitionWriterModelContract } from '../model/models';
import { ChallengeReaderModelContract } from '../model/models';
import { ChallengeWriterModelContract } from '../model/models';
import { QuestionReaderModelContract } from '../model/models';
import { QuestionWriterModelContract } from '../model/models';
import { QuizDefinitionReaderModelContract } from '../model/models';
import { QuizDefinitionWriterModelContract } from '../model/models';
import { QuizItemReaderModelContract } from '../model/models';
import { QuizItemWriterModelContract } from '../model/models';
import { QuizReaderModelContract } from '../model/models';
import { QuizWriterModelContract } from '../model/models';
import { RepositoryReaderModelContract } from '../model/models';
import { RepositoryWriterModelContract } from '../model/models';
import { ReviewReaderModelContract } from '../model/models';
import { ReviewWriterModelContract } from '../model/models';
import { SessionReaderModelContract } from '../model/models';
import { SessionWriterModelContract } from '../model/models';


import { KodinApiConfiguration }                                     from '../kodin.api.configuration';



export interface PutEndPointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: KodinApiConfiguration;

    /**
     *
     *
     * @param id
     * @param challengeDefinitionWriterModelContract
     */
    challengeDefinitionsIdPut(id: string, challengeDefinitionWriterModelContract?: ChallengeDefinitionWriterModelContract, extraHttpRequestParams?: any): Observable<ChallengeDefinitionReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param challengeWriterModelContract
     */
    challengesIdPut(id: string, challengeWriterModelContract?: ChallengeWriterModelContract, extraHttpRequestParams?: any): Observable<ChallengeReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param questionWriterModelContract
     */
    questionsIdPut(id: string, questionWriterModelContract?: QuestionWriterModelContract, extraHttpRequestParams?: any): Observable<QuestionReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param quizDefinitionWriterModelContract
     */
    quizDefinitionsIdPut(id: string, quizDefinitionWriterModelContract?: QuizDefinitionWriterModelContract, extraHttpRequestParams?: any): Observable<QuizDefinitionReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param quizWriterModelContract
     */
    quizzesIdPut(id: string, quizWriterModelContract?: QuizWriterModelContract, extraHttpRequestParams?: any): Observable<QuizReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param quizId
     * @param quizItemWriterModelContract
     */
    quizzesQuizIdQuizItemsPut(id: string, quizId: string, quizItemWriterModelContract?: QuizItemWriterModelContract, extraHttpRequestParams?: any): Observable<QuizItemReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param repositoryWriterModelContract
     */
    repositoriesIdPut(id: string, repositoryWriterModelContract?: RepositoryWriterModelContract, extraHttpRequestParams?: any): Observable<RepositoryReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param reviewWriterModelContract
     */
    reviewsIdPut(id: string, reviewWriterModelContract?: ReviewWriterModelContract, extraHttpRequestParams?: any): Observable<ReviewReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param sessionWriterModelContract
     */
    sessionsIdPut(id: string, sessionWriterModelContract?: SessionWriterModelContract, extraHttpRequestParams?: any): Observable<SessionReaderModelContract>;

}
