/**
 * Admin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { AdminApiConfiguration }                                     from '../admin.api.configuration';



export interface DeleteEndPointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: AdminApiConfiguration;

    /**
     *
     *
     * @param appId
     * @param id
     */
    appsAppIdTermsIdDelete(appId: string, id: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     *
     *
     * @param id
     */
    appsIdDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     *
     *
     * @param id
     */
    languagesIdDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     *
     *
     * @param id
     */
    menuItemsIdDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     *
     *
     * @param id
     */
    userPreferencesIdDelete(id: string, extraHttpRequestParams?: any): Observable<boolean>;

}
