/**
 * Admin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppReaderModelContract } from '../model/models';
import { LanguageReaderModelContract } from '../model/models';
import { MenuItemReaderModelContract } from '../model/models';
import { TermReaderModelContractPagedResult } from '../model/models';
import { UserPreferenceReaderModelContract } from '../model/models';


import { AdminApiConfiguration }                                     from '../admin.api.configuration';



export interface GetAllEndPointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: AdminApiConfiguration;

    /**
     *
     *
     * @param appId
     * @param id
     * @param key
     * @param resourceName
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    appsAppIdTermsGet(appId: string, id?: string, key?: string, resourceName?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<TermReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param name
     * @param key
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    appsGet(id?: string, name?: string, key?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<Array<AppReaderModelContract>>;

    /**
     *
     *
     * @param id
     * @param name
     * @param code
     * @param _native
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    languagesGet(id?: string, name?: string, code?: string, _native?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<Array<LanguageReaderModelContract>>;

    /**
     *
     *
     * @param id
     * @param label
     * @param menuItemId
     * @param appId
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    menuItemsGet(id?: string, label?: string, menuItemId?: string, appId?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<Array<MenuItemReaderModelContract>>;

    /**
     *
     *
     * @param id
     * @param userId
     * @param key
     * @param appId
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    userPreferencesGet(id?: string, userId?: string, key?: string, appId?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<Array<UserPreferenceReaderModelContract>>;

}
