/**
 * Admin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppReaderModelContract } from '../model/models';
import { LanguageReaderModelContract } from '../model/models';
import { MenuItemReaderModelContract } from '../model/models';
import { TermReaderModelContract } from '../model/models';
import { UserPreferenceReaderModelContract } from '../model/models';


import { AdminApiConfiguration }                                     from '../admin.api.configuration';



export interface GetByIdEndPointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: AdminApiConfiguration;

    /**
     *
     *
     * @param appId
     * @param id
     */
    appsAppIdTermsIdGet(appId: string, id: string, extraHttpRequestParams?: any): Observable<TermReaderModelContract>;

    /**
     *
     *
     * @param id
     */
    appsIdGet(id: string, extraHttpRequestParams?: any): Observable<AppReaderModelContract>;

    /**
     *
     *
     * @param id
     */
    languagesIdGet(id: string, extraHttpRequestParams?: any): Observable<LanguageReaderModelContract>;

    /**
     *
     *
     * @param id
     */
    menuItemsIdGet(id: string, extraHttpRequestParams?: any): Observable<MenuItemReaderModelContract>;

    /**
     *
     *
     * @param id
     */
    userPreferencesIdGet(id: string, extraHttpRequestParams?: any): Observable<UserPreferenceReaderModelContract>;

}
