/**
 * Admin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppReaderModelContract } from '../model/models';
import { AppWriterModelContract } from '../model/models';
import { LanguageReaderModelContract } from '../model/models';
import { LanguageWriterModelContract } from '../model/models';
import { MenuItemReaderModelContract } from '../model/models';
import { MenuItemWriterModelContract } from '../model/models';
import { TermReaderModelContract } from '../model/models';
import { TermWriterModelContract } from '../model/models';
import { UserPreferenceReaderModelContract } from '../model/models';
import { UserPreferenceWriterModelContract } from '../model/models';


import { AdminApiConfiguration }                                     from '../admin.api.configuration';



export interface PutEndPointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: AdminApiConfiguration;

    /**
     *
     *
     * @param appId
     * @param id
     * @param termWriterModelContract
     */
    appsAppIdTermsIdPut(appId: string, id: string, termWriterModelContract?: TermWriterModelContract, extraHttpRequestParams?: any): Observable<TermReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param appWriterModelContract
     */
    appsIdPut(id: string, appWriterModelContract?: AppWriterModelContract, extraHttpRequestParams?: any): Observable<AppReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param languageWriterModelContract
     */
    languagesIdPut(id: string, languageWriterModelContract?: LanguageWriterModelContract, extraHttpRequestParams?: any): Observable<LanguageReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param menuItemWriterModelContract
     */
    menuItemsIdPut(id: string, menuItemWriterModelContract?: MenuItemWriterModelContract, extraHttpRequestParams?: any): Observable<MenuItemReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param userPreferenceWriterModelContract
     */
    userPreferencesIdPut(id: string, userPreferenceWriterModelContract?: UserPreferenceWriterModelContract, extraHttpRequestParams?: any): Observable<UserPreferenceReaderModelContract>;

}
