/**
 * Kodin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ChallengeDefinitionState = 0 | 1 | 2 | 3;

export const ChallengeDefinitionState = {
    NUMBER_0: 0 as ChallengeDefinitionState,
    NUMBER_1: 1 as ChallengeDefinitionState,
    NUMBER_2: 2 as ChallengeDefinitionState,
    NUMBER_3: 3 as ChallengeDefinitionState
};

