/**
 * Kodin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChallengeDefinitionState } from './challengeDefinitionState';
import { SourceCodeReduceModelContract } from './sourceCodeReduceModelContract';
import { UnitTestReduceModelContract } from './unitTestReduceModelContract';


export interface ChallengeDefinitionReaderModelContract { 
    id?: string | null;
    title?: string | null;
    resume?: string | null;
    state?: ChallengeDefinitionState;
    description?: string | null;
    instruction?: string | null;
    score?: number | null;
    timeLimit?: number | null;
    withLimit?: boolean | null;
    createdBy?: string | null;
    created?: string | null;
    lastModifiedBy?: string | null;
    lastModified?: string | null;
    organizationId?: string | null;
    visibility?: string | null;
    unitTests?: Array<UnitTestReduceModelContract> | null;
    sourceCodes?: Array<SourceCodeReduceModelContract> | null;
    level?: any | null;
    skills?: Array<any> | null;
    topics?: Array<any> | null;
}
export namespace ChallengeDefinitionReaderModelContract {
}


