/**
 * Kodin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizState } from './quizState';
import { QuizDefinitionReduceModelContract } from './quizDefinitionReduceModelContract';
import { SessionReduceModelContract } from './sessionReduceModelContract';


export interface QuizReaderModelContract { 
    id?: string | null;
    startDateTime?: string | null;
    endDateTime?: string | null;
    state?: QuizState;
    createdBy?: string | null;
    created?: string | null;
    lastModifiedBy?: string | null;
    lastModified?: string | null;
    organizationId?: string | null;
    visibility?: string | null;
    quizDefinition?: QuizDefinitionReduceModelContract;
    session?: SessionReduceModelContract;
    user?: any | null;
}
export namespace QuizReaderModelContract {
}


