/**
 * Kodin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizDefinitionState } from './quizDefinitionState';


export interface QuizDefinitionWriterModelContract { 
    title?: string | null;
    description?: string | null;
    instruction?: string | null;
    state?: QuizDefinitionState;
    language?: string | null;
    questionsId: Array<string>;
    levelId: string;
    skillsId: Array<string>;
    topicsId: Array<string>;
}
export namespace QuizDefinitionWriterModelContract {
}


