/**
 * Kodin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionReduceModelContract } from './questionReduceModelContract';
import { QuizDefinitionState } from './quizDefinitionState';


export interface QuizDefinitionReaderModelContract { 
    id?: string | null;
    title?: string | null;
    description?: string | null;
    instruction?: string | null;
    state?: QuizDefinitionState;
    language?: string | null;
    createdBy?: string | null;
    created?: string | null;
    lastModifiedBy?: string | null;
    lastModified?: string | null;
    organizationId?: string | null;
    visibility?: string | null;
    questions?: Array<QuestionReduceModelContract> | null;
    level?: any | null;
    skills?: Array<any> | null;
    topics?: Array<any> | null;
}
export namespace QuizDefinitionReaderModelContract {
}


