/**
 * Kodin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RepositoryReduceModelContract } from './repositoryReduceModelContract';
import { RepositoryState } from './repositoryState';


export interface RepositoryReaderModelContract { 
    id?: string | null;
    name?: string | null;
    url?: string | null;
    description?: string | null;
    instruction?: string | null;
    fork?: boolean | null;
    state?: RepositoryState;
    createdBy?: string | null;
    created?: string | null;
    lastModifiedBy?: string | null;
    lastModified?: string | null;
    organizationId?: string | null;
    visibility?: string | null;
    user?: any | null;
    developmentEnvironment?: any | null;
    origin?: RepositoryReduceModelContract;
    level?: any | null;
    skills?: Array<any> | null;
    topics?: Array<any> | null;
}
export namespace RepositoryReaderModelContract {
}


