/**
 * Kodin.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionReduceModelContract } from './sessionReduceModelContract';
import { ReviewItemReduceModelContract } from './reviewItemReduceModelContract';


export interface ReviewReaderModelContract { 
    id?: string | null;
    title?: string | null;
    description?: string | null;
    reviewDateTime?: string | null;
    organizationId?: string | null;
    visibility?: string | null;
    reviewer?: any | null;
    session?: SessionReduceModelContract;
    reviewItems?: Array<ReviewItemReduceModelContract> | null;
}

