/**
 * ReferenceItems.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReferenceItemReaderModelContract { 
    id?: string;
    key?: string;
    entity?: string;
    imageUrl?: string;
    properties?: object;
    value?: string;
    language?: string;
    visibility?: string;
}

