/**
 * ReferenceItems.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReferenceItemReaderModelContract } from './referenceItemReaderModelContract';


export interface ReferenceItemReaderModelContractPagedResult { 
    page?: number;
    pageCount?: number;
    limit?: number;
    rowCount?: number;
    readonly firstRowOnPage?: number;
    readonly lastRowOnPage?: number;
    items?: Array<ReferenceItemReaderModelContract>;
}

