/**
 * Identities.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppReaderModelContractPagedResult } from '../model/models';
import { ChallengeDefinitionReaderModelContractPagedResult } from '../model/models';
import { ChallengeDefinitionState } from '../model/models';
import { ChallengeReaderModelContractPagedResult } from '../model/models';
import { FeatureReaderModelContractPagedResult } from '../model/models';
import { LicenseReaderModelContractPagedResult } from '../model/models';
import { MembershipReaderModelContractPagedResult } from '../model/models';
import { OrganizationReaderModelContractPagedResult } from '../model/models';
import { OrganizationState } from '../model/models';
import { PersonReaderModelContract } from '../model/models';
import { QuestionReaderModelContractPagedResult } from '../model/models';
import { QuestionType } from '../model/models';
import { QuizDefinitionReaderModelContractPagedResult } from '../model/models';
import { QuizItemReaderModelContractPagedResult } from '../model/models';
import { QuizReaderModelContractPagedResult } from '../model/models';
import { RepositoryReaderModelContractPagedResult } from '../model/models';
import { RepositoryState } from '../model/models';
import { ReviewReaderModelContractPagedResult } from '../model/models';
import { RoleReaderModelContractPagedResult } from '../model/models';
import { SessionReaderModelContractPagedResult } from '../model/models';
import { SubscriptionReaderModelContractPagedResult } from '../model/models';
import { UserReaderModelContractPagedResult } from '../model/models';


import { IdentitiesApiConfiguration }                                     from '../identities.api.configuration';



export interface GetAllEndPointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: IdentitiesApiConfiguration;

    /**
     *
     *
     * @param appId
     * @param id
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    appsAppIdFeaturesGet(appId: string, id?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<FeatureReaderModelContractPagedResult>;

    /**
     *
     *
     * @param appId2
     * @param id
     * @param appId
     * @param name
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    appsAppIdRolesGet(appId2: string, id?: string, appId?: string, name?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<RoleReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param name
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    appsGet(id?: string, name?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<AppReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param title
     * @param state
     * @param withLimit
     * @param levelId
     * @param skillsId
     * @param topicsId
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    challengeDefinitionsGet(id?: string, title?: string, state?: ChallengeDefinitionState, withLimit?: boolean, levelId?: string, skillsId?: Array<string>, topicsId?: Array<string>, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<ChallengeDefinitionReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param challengeDefinitionId
     * @param userId
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    challengesGet(id?: string, challengeDefinitionId?: string, userId?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<ChallengeReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param userId
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    membershipsGet(id?: string, userId?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<MembershipReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param name
     * @param domain
     * @param state
     * @param userId
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    organizationsGet(id?: string, name?: string, domain?: string, state?: OrganizationState, userId?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<OrganizationReaderModelContractPagedResult>;

    /**
     *
     *
     * @param organizationId
     * @param id
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    organizationsOrganizationIdSubscriptionsGet(organizationId: string, id?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<SubscriptionReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    personsGet(id?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<Array<PersonReaderModelContract>>;

    /**
     *
     *
     * @param id
     * @param title
     * @param questionType
     * @param withLimit
     * @param language
     * @param questionCategoryId
     * @param levelId
     * @param skillsId
     * @param topicsId
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    questionsGet(id?: string, title?: string, questionType?: QuestionType, withLimit?: boolean, language?: string, questionCategoryId?: string, levelId?: string, skillsId?: Array<string>, topicsId?: Array<string>, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<QuestionReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param title
     * @param language
     * @param levelId
     * @param skillsId
     * @param topicsId
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    quizDefinitionsGet(id?: string, title?: string, language?: string, levelId?: string, skillsId?: Array<string>, topicsId?: Array<string>, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<QuizDefinitionReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param quizDefinitionId
     * @param userId
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    quizzesGet(id?: string, quizDefinitionId?: string, userId?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<QuizReaderModelContractPagedResult>;

    /**
     *
     *
     * @param quizId
     * @param id
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    quizzesQuizIdQuizItemsGet(quizId: string, id?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<QuizItemReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param name
     * @param url
     * @param fork
     * @param state
     * @param userId
     * @param developmentEnvironmentId
     * @param levelId
     * @param skillsId
     * @param topicsId
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    repositoriesGet(id?: string, name?: string, url?: string, fork?: boolean, state?: RepositoryState, userId?: string, developmentEnvironmentId?: string, levelId?: string, skillsId?: Array<string>, topicsId?: Array<string>, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<RepositoryReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param userId
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    reviewsGet(id?: string, userId?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<ReviewReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param userId
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    sessionsGet(id?: string, userId?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<SessionReaderModelContractPagedResult>;

    /**
     *
     *
     * @param id
     * @param firstname
     * @param lastname
     * @param username
     * @param language
     * @param locale
     * @param email
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    usersGet(id?: string, firstname?: string, lastname?: string, username?: string, language?: string, locale?: string, email?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<UserReaderModelContractPagedResult>;

    /**
     *
     *
     * @param userId
     * @param subscriptionId
     * @param id
     * @param name
     * @param page
     * @param limit
     * @param q
     * @param orders
     */
    usersUserIdSubscriptionsSubscriptionIdLicensesGet(userId: string, subscriptionId: string, id?: string, name?: string, page?: number, limit?: number, q?: string, orders?: Array<string>, extraHttpRequestParams?: any): Observable<LicenseReaderModelContractPagedResult>;

}
