/**
 * Identities.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppReaderModelContract } from '../model/models';
import { AppWriterModelContract } from '../model/models';
import { ChallengeDefinitionReaderModelContract } from '../model/models';
import { ChallengeDefinitionWriterModelContract } from '../model/models';
import { ChallengeReaderModelContract } from '../model/models';
import { ChallengeWriterModelContract } from '../model/models';
import { FeatureReaderModelContract } from '../model/models';
import { FeatureWriterModelContract } from '../model/models';
import { LicenseReaderModelContract } from '../model/models';
import { LicenseWriterModelContract } from '../model/models';
import { MembershipReaderModelContract } from '../model/models';
import { MembershipWriterModelContract } from '../model/models';
import { OrganizationReaderModelContract } from '../model/models';
import { OrganizationWriterModelContract } from '../model/models';
import { PersonReaderModelContract } from '../model/models';
import { PersonWriterModelContract } from '../model/models';
import { QuestionReaderModelContract } from '../model/models';
import { QuestionWriterModelContract } from '../model/models';
import { QuizDefinitionReaderModelContract } from '../model/models';
import { QuizDefinitionWriterModelContract } from '../model/models';
import { QuizItemReaderModelContract } from '../model/models';
import { QuizItemWriterModelContract } from '../model/models';
import { QuizReaderModelContract } from '../model/models';
import { QuizWriterModelContract } from '../model/models';
import { RepositoryReaderModelContract } from '../model/models';
import { RepositoryWriterModelContract } from '../model/models';
import { ReviewReaderModelContract } from '../model/models';
import { ReviewWriterModelContract } from '../model/models';
import { RoleReaderModelContract } from '../model/models';
import { RoleWriterModelContract } from '../model/models';
import { ScopeReaderModelContract } from '../model/models';
import { ScopeWriterModelContract } from '../model/models';
import { SessionReaderModelContract } from '../model/models';
import { SessionWriterModelContract } from '../model/models';
import { SubscriptionReaderModelContract } from '../model/models';
import { SubscriptionWriterModelContract } from '../model/models';
import { UserReaderModelContract } from '../model/models';
import { UserWriterModelContract } from '../model/models';


import { IdentitiesApiConfiguration }                                     from '../identities.api.configuration';



export interface PostEndPointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: IdentitiesApiConfiguration;

    /**
     *
     *
     * @param appId
     * @param featureWriterModelContract
     */
    appsAppIdFeaturesPost(appId: string, featureWriterModelContract?: FeatureWriterModelContract, extraHttpRequestParams?: any): Observable<FeatureReaderModelContract>;

    /**
     *
     *
     * @param appId
     * @param roleWriterModelContract
     */
    appsAppIdRolesPost(appId: string, roleWriterModelContract?: RoleWriterModelContract, extraHttpRequestParams?: any): Observable<RoleReaderModelContract>;

    /**
     *
     *
     * @param appWriterModelContract
     */
    appsPost(appWriterModelContract?: AppWriterModelContract, extraHttpRequestParams?: any): Observable<AppReaderModelContract>;

    /**
     *
     *
     * @param challengeDefinitionWriterModelContract
     */
    challengeDefinitionsPost(challengeDefinitionWriterModelContract?: ChallengeDefinitionWriterModelContract, extraHttpRequestParams?: any): Observable<ChallengeDefinitionReaderModelContract>;

    /**
     *
     *
     * @param challengeWriterModelContract
     */
    challengesPost(challengeWriterModelContract?: ChallengeWriterModelContract, extraHttpRequestParams?: any): Observable<ChallengeReaderModelContract>;

    /**
     *
     *
     * @param membershipWriterModelContract
     */
    membershipsPost(membershipWriterModelContract?: MembershipWriterModelContract, extraHttpRequestParams?: any): Observable<MembershipReaderModelContract>;

    /**
     *
     *
     * @param organizationId
     * @param id
     * @param subscriptionWriterModelContract
     */
    organizationsOrganizationIdSubscriptionsPost(organizationId: string, id: string, subscriptionWriterModelContract?: SubscriptionWriterModelContract, extraHttpRequestParams?: any): Observable<SubscriptionReaderModelContract>;

    /**
     *
     *
     * @param organizationWriterModelContract
     */
    organizationsPost(organizationWriterModelContract?: OrganizationWriterModelContract, extraHttpRequestParams?: any): Observable<OrganizationReaderModelContract>;

    /**
     *
     *
     * @param personWriterModelContract
     */
    personsPost(personWriterModelContract?: PersonWriterModelContract, extraHttpRequestParams?: any): Observable<PersonReaderModelContract>;

    /**
     *
     *
     * @param questionWriterModelContract
     */
    questionsPost(questionWriterModelContract?: QuestionWriterModelContract, extraHttpRequestParams?: any): Observable<QuestionReaderModelContract>;

    /**
     *
     *
     * @param quizDefinitionWriterModelContract
     */
    quizDefinitionsPost(quizDefinitionWriterModelContract?: QuizDefinitionWriterModelContract, extraHttpRequestParams?: any): Observable<QuizDefinitionReaderModelContract>;

    /**
     *
     *
     * @param quizWriterModelContract
     */
    quizzesPost(quizWriterModelContract?: QuizWriterModelContract, extraHttpRequestParams?: any): Observable<QuizReaderModelContract>;

    /**
     *
     *
     * @param quizId
     * @param quizItemWriterModelContract
     */
    quizzesQuizIdQuizItemsPost(quizId: string, quizItemWriterModelContract?: QuizItemWriterModelContract, extraHttpRequestParams?: any): Observable<QuizItemReaderModelContract>;

    /**
     *
     *
     * @param repositoryWriterModelContract
     */
    repositoriesPost(repositoryWriterModelContract?: RepositoryWriterModelContract, extraHttpRequestParams?: any): Observable<RepositoryReaderModelContract>;

    /**
     *
     *
     * @param reviewWriterModelContract
     */
    reviewsPost(reviewWriterModelContract?: ReviewWriterModelContract, extraHttpRequestParams?: any): Observable<ReviewReaderModelContract>;

    /**
     *
     *
     * @param scopeWriterModelContract
     */
    scopesPost(scopeWriterModelContract?: ScopeWriterModelContract, extraHttpRequestParams?: any): Observable<ScopeReaderModelContract>;

    /**
     *
     *
     * @param sessionWriterModelContract
     */
    sessionsPost(sessionWriterModelContract?: SessionWriterModelContract, extraHttpRequestParams?: any): Observable<SessionReaderModelContract>;

    /**
     *
     *
     * @param userWriterModelContract
     */
    usersPost(userWriterModelContract?: UserWriterModelContract, extraHttpRequestParams?: any): Observable<UserReaderModelContract>;

    /**
     *
     *
     * @param userId
     * @param subscriptionId
     * @param licenseWriterModelContract
     */
    usersUserIdSubscriptionsSubscriptionIdLicensesPost(userId: string, subscriptionId: string, licenseWriterModelContract?: LicenseWriterModelContract, extraHttpRequestParams?: any): Observable<LicenseReaderModelContract>;

}
