/**
 * Identities.Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppReaderModelContract } from '../model/models';
import { AppWriterModelContract } from '../model/models';
import { ChallengeDefinitionReaderModelContract } from '../model/models';
import { ChallengeDefinitionWriterModelContract } from '../model/models';
import { ChallengeReaderModelContract } from '../model/models';
import { ChallengeWriterModelContract } from '../model/models';
import { FeatureReaderModelContract } from '../model/models';
import { FeatureWriterModelContract } from '../model/models';
import { LicenseReaderModelContract } from '../model/models';
import { LicenseWriterModelContract } from '../model/models';
import { MembershipReaderModelContract } from '../model/models';
import { MembershipUpdaterModelContract } from '../model/models';
import { OrganizationEventModelContract } from '../model/models';
import { OrganizationReaderModelContract } from '../model/models';
import { OrganizationWriterModelContract } from '../model/models';
import { PersonReaderModelContract } from '../model/models';
import { PersonWriterModelContract } from '../model/models';
import { QuestionReaderModelContract } from '../model/models';
import { QuestionWriterModelContract } from '../model/models';
import { QuizDefinitionReaderModelContract } from '../model/models';
import { QuizDefinitionWriterModelContract } from '../model/models';
import { QuizItemReaderModelContract } from '../model/models';
import { QuizItemWriterModelContract } from '../model/models';
import { QuizReaderModelContract } from '../model/models';
import { QuizWriterModelContract } from '../model/models';
import { RepositoryReaderModelContract } from '../model/models';
import { RepositoryWriterModelContract } from '../model/models';
import { ReviewReaderModelContract } from '../model/models';
import { ReviewWriterModelContract } from '../model/models';
import { RoleReaderModelContract } from '../model/models';
import { RoleWriterModelContract } from '../model/models';
import { SessionReaderModelContract } from '../model/models';
import { SessionWriterModelContract } from '../model/models';
import { SubscriptionReaderModelContract } from '../model/models';
import { SubscriptionWriterModelContract } from '../model/models';
import { UserReaderModelContract } from '../model/models';
import { UserUpdaterModelContract } from '../model/models';


import { IdentitiesApiConfiguration }                                     from '../identities.api.configuration';



export interface PutEndPointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: IdentitiesApiConfiguration;

    /**
     *
     *
     * @param appId
     * @param id
     * @param featureWriterModelContract
     */
    appsAppIdFeaturesIdPut(appId: string, id: string, featureWriterModelContract?: FeatureWriterModelContract, extraHttpRequestParams?: any): Observable<FeatureReaderModelContract>;

    /**
     *
     *
     * @param appId
     * @param id
     * @param roleWriterModelContract
     */
    appsAppIdRolesIdPut(appId: string, id: string, roleWriterModelContract?: RoleWriterModelContract, extraHttpRequestParams?: any): Observable<RoleReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param appWriterModelContract
     */
    appsIdPut(id: string, appWriterModelContract?: AppWriterModelContract, extraHttpRequestParams?: any): Observable<AppReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param challengeDefinitionWriterModelContract
     */
    challengeDefinitionsIdPut(id: string, challengeDefinitionWriterModelContract?: ChallengeDefinitionWriterModelContract, extraHttpRequestParams?: any): Observable<ChallengeDefinitionReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param challengeWriterModelContract
     */
    challengesIdPut(id: string, challengeWriterModelContract?: ChallengeWriterModelContract, extraHttpRequestParams?: any): Observable<ChallengeReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param membershipUpdaterModelContract
     */
    membershipsIdPut(id: string, membershipUpdaterModelContract?: MembershipUpdaterModelContract, extraHttpRequestParams?: any): Observable<MembershipReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param organizationEventModelContract
     */
    organizationsIdEventsPut(id: string, organizationEventModelContract?: OrganizationEventModelContract, extraHttpRequestParams?: any): Observable<OrganizationReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param organizationWriterModelContract
     */
    organizationsIdPut(id: string, organizationWriterModelContract?: OrganizationWriterModelContract, extraHttpRequestParams?: any): Observable<OrganizationReaderModelContract>;

    /**
     *
     *
     * @param organizationId
     * @param id
     * @param subscriptionWriterModelContract
     */
    organizationsOrganizationIdSubscriptionsIdPut(organizationId: string, id: string, subscriptionWriterModelContract?: SubscriptionWriterModelContract, extraHttpRequestParams?: any): Observable<SubscriptionReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param personWriterModelContract
     */
    personsIdPut(id: string, personWriterModelContract?: PersonWriterModelContract, extraHttpRequestParams?: any): Observable<PersonReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param questionWriterModelContract
     */
    questionsIdPut(id: string, questionWriterModelContract?: QuestionWriterModelContract, extraHttpRequestParams?: any): Observable<QuestionReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param quizDefinitionWriterModelContract
     */
    quizDefinitionsIdPut(id: string, quizDefinitionWriterModelContract?: QuizDefinitionWriterModelContract, extraHttpRequestParams?: any): Observable<QuizDefinitionReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param quizWriterModelContract
     */
    quizzesIdPut(id: string, quizWriterModelContract?: QuizWriterModelContract, extraHttpRequestParams?: any): Observable<QuizReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param quizId
     * @param quizItemWriterModelContract
     */
    quizzesQuizIdQuizItemsPut(id: string, quizId: string, quizItemWriterModelContract?: QuizItemWriterModelContract, extraHttpRequestParams?: any): Observable<QuizItemReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param repositoryWriterModelContract
     */
    repositoriesIdPut(id: string, repositoryWriterModelContract?: RepositoryWriterModelContract, extraHttpRequestParams?: any): Observable<RepositoryReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param reviewWriterModelContract
     */
    reviewsIdPut(id: string, reviewWriterModelContract?: ReviewWriterModelContract, extraHttpRequestParams?: any): Observable<ReviewReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param sessionWriterModelContract
     */
    sessionsIdPut(id: string, sessionWriterModelContract?: SessionWriterModelContract, extraHttpRequestParams?: any): Observable<SessionReaderModelContract>;

    /**
     *
     *
     * @param id
     * @param userUpdaterModelContract
     */
    usersIdPut(id: string, userUpdaterModelContract?: UserUpdaterModelContract, extraHttpRequestParams?: any): Observable<UserReaderModelContract>;

    /**
     *
     *
     * @param userId
     * @param body
     */
    usersUserIdMembershipsDefaultPut(userId: string, body?: string, extraHttpRequestParams?: any): Observable<MembershipReaderModelContract>;

    /**
     *
     *
     * @param userId
     * @param subscriptionId
     * @param id
     * @param licenseWriterModelContract
     */
    usersUserIdSubscriptionsSubscriptionIdLicensesIdPut(userId: string, subscriptionId: string, id: string, licenseWriterModelContract?: LicenseWriterModelContract, extraHttpRequestParams?: any): Observable<LicenseReaderModelContract>;

}
